[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true

[tool.isort]
profile = "black"

[tool.black]
